'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { DatabaseSync } = require('node:sqlite');

const POSTGRES_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  is_verified_customer INTEGER NOT NULL DEFAULT 0 CHECK (is_verified_customer IN (0,1)),
  verified_customer_at BIGINT,
  created_at BIGINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_nocase ON users (LOWER(email));

CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_ref TEXT NOT NULL UNIQUE,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  customer_email TEXT,
  customer_phone TEXT,
  amount_agorot INTEGER NOT NULL,
  currency TEXT NOT NULL DEFAULT 'ILS',
  items_json TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','failed')),
  created_at BIGINT NOT NULL,
  paid_at BIGINT,
  updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  review_name TEXT,
  contact_phone TEXT,
  verified_purchase INTEGER NOT NULL DEFAULT 0 CHECK (verified_purchase IN (0,1)),
  review_product_id TEXT,
  review_product_variant TEXT,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  body TEXT NOT NULL,
  review_date BIGINT,
  image_blob BYTEA,
  image_mime TEXT,
  status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('published','hidden')),
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS review_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id INTEGER NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL,
  image_blob BYTEA NOT NULL,
  image_mime TEXT NOT NULL,
  media_kind TEXT NOT NULL DEFAULT 'image' CHECK (media_kind IN ('image','video')),
  created_at BIGINT NOT NULL,
  UNIQUE (review_id, sort_order)
);


CREATE TABLE IF NOT EXISTS visitor_presence (
  visitor_id TEXT PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  is_authenticated INTEGER NOT NULL DEFAULT 0 CHECK (is_authenticated IN (0,1)),
  first_seen BIGINT NOT NULL,
  last_seen BIGINT NOT NULL,
  current_path TEXT NOT NULL DEFAULT '/',
  entry_path TEXT NOT NULL DEFAULT '/',
  last_title TEXT,
  referrer TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_term TEXT,
  utm_content TEXT,
  language TEXT,
  browser TEXT,
  os TEXT,
  device_type TEXT,
  screen_width INTEGER,
  screen_height INTEGER,
  viewport_width INTEGER,
  viewport_height INTEGER,
  page_view_count INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE visitor_presence ADD COLUMN IF NOT EXISTS is_authenticated INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS visitor_page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_id TEXT NOT NULL REFERENCES visitor_presence(visitor_id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  path TEXT NOT NULL,
  title TEXT,
  referrer TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_term TEXT,
  utm_content TEXT,
  viewed_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS schema_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_orders_ref ON orders(order_ref);
CREATE INDEX IF NOT EXISTS idx_orders_user_status ON orders(user_id, status);
CREATE INDEX IF NOT EXISTS idx_reviews_status_created_at ON reviews(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_review_images_review_order ON review_images(review_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_visitor_presence_last_seen ON visitor_presence(last_seen DESC);
CREATE INDEX IF NOT EXISTS idx_visitor_presence_user_id ON visitor_presence(user_id);
CREATE INDEX IF NOT EXISTS idx_visitor_page_views_visitor_time ON visitor_page_views(visitor_id, viewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_visitor_page_views_user_time ON visitor_page_views(user_id, viewed_at DESC);
`;

const PRODUCT_REPLACEMENT_REVIEW_RESETS = [
  {
    key: 'product_replacement_review_reset_product10_v1',
    reviewProductIds: ['wife-necklace-only-01']
  },
  {
    key: 'product_replacement_review_reset_product11_v1',
    reviewProductIds: ['gold-clover-set-01']
  },
  {
    key: 'product_replacement_review_reset_product12_v1',
    reviewProductIds: ['silver-clover-set-01']
  },
  {
    key: 'product_replacement_review_reset_product13_v1',
    reviewProductIds: ['tennis-bracelet-4mm-01']
  }
];

async function applyProductReplacementReviewResets(store) {
  for (const reset of PRODUCT_REPLACEMENT_REVIEW_RESETS) {
    const alreadyApplied = await store.getSchemaMeta(reset.key);
    if (alreadyApplied) continue;
    await store.deleteReviewsByProductIds(reset.reviewProductIds);
    await store.setSchemaMeta(reset.key, String(Date.now()));
  }
}

function ensureSqliteSchema(db) {
  db.exec(`
    PRAGMA journal_mode = WAL;
    PRAGMA foreign_keys = ON;
    PRAGMA busy_timeout = 5000;

    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE COLLATE NOCASE,
      password_hash TEXT NOT NULL,
      is_verified_customer INTEGER NOT NULL DEFAULT 0 CHECK (is_verified_customer IN (0,1)),
      verified_customer_at INTEGER,
      created_at INTEGER NOT NULL
    );

    CREATE TABLE IF NOT EXISTS sessions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      token_hash TEXT NOT NULL UNIQUE,
      created_at INTEGER NOT NULL,
      expires_at INTEGER NOT NULL,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS orders (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      order_ref TEXT NOT NULL UNIQUE,
      user_id INTEGER,
      customer_email TEXT,
      customer_phone TEXT,
      amount_agorot INTEGER NOT NULL,
      currency TEXT NOT NULL DEFAULT 'ILS',
      items_json TEXT,
      status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','failed')),
      created_at INTEGER NOT NULL,
      paid_at INTEGER,
      updated_at INTEGER NOT NULL,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    );

    CREATE TABLE IF NOT EXISTS reviews (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      review_name TEXT,
      contact_phone TEXT,
      verified_purchase INTEGER NOT NULL DEFAULT 0 CHECK (verified_purchase IN (0,1)),
      review_product_id TEXT,
      review_product_variant TEXT,
      rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
      body TEXT NOT NULL,
      review_date INTEGER,
      image_blob BLOB,
      image_mime TEXT,
      status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('published','hidden')),
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS review_images (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      review_id INTEGER NOT NULL,
      sort_order INTEGER NOT NULL,
      image_blob BLOB NOT NULL,
      image_mime TEXT NOT NULL,
      media_kind TEXT NOT NULL DEFAULT 'image' CHECK (media_kind IN ('image','video')),
      created_at INTEGER NOT NULL,
      FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
      UNIQUE (review_id, sort_order)
    );


    CREATE TABLE IF NOT EXISTS visitor_presence (
      visitor_id TEXT PRIMARY KEY,
      user_id INTEGER,
      is_authenticated INTEGER NOT NULL DEFAULT 0 CHECK (is_authenticated IN (0,1)),
      first_seen INTEGER NOT NULL,
      last_seen INTEGER NOT NULL,
      current_path TEXT NOT NULL DEFAULT '/',
      entry_path TEXT NOT NULL DEFAULT '/',
      last_title TEXT,
      referrer TEXT,
      utm_source TEXT,
      utm_medium TEXT,
      utm_campaign TEXT,
      utm_term TEXT,
      utm_content TEXT,
      language TEXT,
      browser TEXT,
      os TEXT,
      device_type TEXT,
      screen_width INTEGER,
      screen_height INTEGER,
      viewport_width INTEGER,
      viewport_height INTEGER,
      page_view_count INTEGER NOT NULL DEFAULT 0,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    );

    CREATE TABLE IF NOT EXISTS visitor_page_views (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      visitor_id TEXT NOT NULL,
      user_id INTEGER,
      path TEXT NOT NULL,
      title TEXT,
      referrer TEXT,
      utm_source TEXT,
      utm_medium TEXT,
      utm_campaign TEXT,
      utm_term TEXT,
      utm_content TEXT,
      viewed_at INTEGER NOT NULL,
      FOREIGN KEY (visitor_id) REFERENCES visitor_presence(visitor_id) ON DELETE CASCADE,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    );

    CREATE TABLE IF NOT EXISTS schema_meta (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    );
  `);

  const addColumnIfMissing = (table, column, sql) => {
    const columns = db.prepare(`PRAGMA table_info(${table})`).all();
    if (!columns.some((item) => item.name === column)) db.exec(sql);
  };
  addColumnIfMissing('users', 'is_verified_customer', 'ALTER TABLE users ADD COLUMN is_verified_customer INTEGER NOT NULL DEFAULT 0 CHECK (is_verified_customer IN (0,1))');
  addColumnIfMissing('users', 'verified_customer_at', 'ALTER TABLE users ADD COLUMN verified_customer_at INTEGER');
  addColumnIfMissing('reviews', 'review_name', 'ALTER TABLE reviews ADD COLUMN review_name TEXT');
  addColumnIfMissing('reviews', 'review_date', 'ALTER TABLE reviews ADD COLUMN review_date INTEGER');
  addColumnIfMissing('reviews', 'contact_phone', 'ALTER TABLE reviews ADD COLUMN contact_phone TEXT');
  addColumnIfMissing('reviews', 'verified_purchase', 'ALTER TABLE reviews ADD COLUMN verified_purchase INTEGER NOT NULL DEFAULT 0 CHECK (verified_purchase IN (0,1))');
  addColumnIfMissing('reviews', 'review_product_id', 'ALTER TABLE reviews ADD COLUMN review_product_id TEXT');
  addColumnIfMissing('reviews', 'review_product_variant', 'ALTER TABLE reviews ADD COLUMN review_product_variant TEXT');
  addColumnIfMissing('review_images', 'media_kind', "ALTER TABLE review_images ADD COLUMN media_kind TEXT NOT NULL DEFAULT 'image' CHECK (media_kind IN ('image','video'))");
  addColumnIfMissing('visitor_presence', 'is_authenticated', "ALTER TABLE visitor_presence ADD COLUMN is_authenticated INTEGER NOT NULL DEFAULT 0 CHECK (is_authenticated IN (0,1))");

  db.exec(`
    CREATE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash);
    CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
    CREATE INDEX IF NOT EXISTS idx_orders_ref ON orders(order_ref);
    CREATE INDEX IF NOT EXISTS idx_orders_user_status ON orders(user_id, status);
    CREATE INDEX IF NOT EXISTS idx_reviews_status_created_at ON reviews(status, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_review_images_review_order ON review_images(review_id, sort_order);
    CREATE INDEX IF NOT EXISTS idx_visitor_presence_last_seen ON visitor_presence(last_seen DESC);
    CREATE INDEX IF NOT EXISTS idx_visitor_presence_user_id ON visitor_presence(user_id);
    CREATE INDEX IF NOT EXISTS idx_visitor_page_views_visitor_time ON visitor_page_views(visitor_id, viewed_at DESC);
    CREATE INDEX IF NOT EXISTS idx_visitor_page_views_user_time ON visitor_page_views(user_id, viewed_at DESC);
    UPDATE reviews SET review_name = 'לקוח VerSans';
    UPDATE reviews SET review_date = created_at WHERE review_date IS NULL;
    UPDATE reviews SET review_product_id = 'mom-heart-01' WHERE review_product_id IS NULL OR review_product_id = '';
    INSERT INTO review_images (review_id, sort_order, image_blob, image_mime, media_kind, created_at)
      SELECT r.id, 0, r.image_blob, r.image_mime, 'image', r.created_at
      FROM reviews r
      WHERE r.image_blob IS NOT NULL AND r.image_mime IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM review_images ri WHERE ri.review_id = r.id);
    INSERT INTO schema_meta (key, value) VALUES ('schema_version', '9')
      ON CONFLICT(key) DO UPDATE SET value = excluded.value;
  `);
}

class SqliteStore {
  constructor(sqlitePath) {
    this.backend = 'sqlite';
    this.sqlitePath = sqlitePath;
    this.db = null;
  }

  async init() {
    fs.mkdirSync(path.dirname(this.sqlitePath), { recursive: true });
    this.db = new DatabaseSync(this.sqlitePath);
    ensureSqliteSchema(this.db);
    await this.deleteExpiredSessions(Date.now());
    await applyProductReplacementReviewResets(this);
    return this;
  }

  async close() { if (this.db) { this.db.close(); this.db = null; } }

  async getSchemaMeta(key) { const row = this.db.prepare('SELECT value FROM schema_meta WHERE key=? LIMIT 1').get(key); return row ? String(row.value) : null; }
  async setSchemaMeta(key, value) { this.db.prepare(`INSERT INTO schema_meta (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value`).run(key, String(value)); }
  async deleteReviewsByProductIds(productIds) { if (!Array.isArray(productIds) || !productIds.length) return { reviews: 0 }; const placeholders = productIds.map(() => '?').join(','); const result = this.db.prepare(`DELETE FROM reviews WHERE review_product_id IN (${placeholders})`).run(...productIds); return { reviews: Number(result.changes || 0) }; }

  async transaction(fn) {
    this.db.exec('BEGIN IMMEDIATE');
    try {
      const value = await fn(this);
      this.db.exec('COMMIT');
      return value;
    } catch (err) {
      try { this.db.exec('ROLLBACK'); } catch (_) {}
      throw err;
    }
  }

  async findUserByEmail(email) { return this.db.prepare(`SELECT id, name, email, password_hash, is_verified_customer, verified_customer_at, created_at FROM users WHERE email = ? COLLATE NOCASE LIMIT 1`).get(email) || null; }
  async findPublicUserBySession(hash, now) { return this.db.prepare(`SELECT u.id, u.name, u.email, u.is_verified_customer, u.verified_customer_at, u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? LIMIT 1`).get(hash, now) || null; }
  async insertUser(name, email, passwordHash, createdAt) { const r = this.db.prepare('INSERT INTO users (name,email,password_hash,created_at) VALUES (?,?,?,?)').run(name,email,passwordHash,createdAt); return Number(r.lastInsertRowid); }
  async insertSession(userId, tokenHash, createdAt, expiresAt) { this.db.prepare('INSERT INTO sessions (user_id,token_hash,created_at,expires_at) VALUES (?,?,?,?)').run(userId,tokenHash,createdAt,expiresAt); }
  async deleteSession(hash) { this.db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash); }
  async deleteExpiredSessions(now) { this.db.prepare('DELETE FROM sessions WHERE expires_at<=?').run(now); }

  _reviewSelect(where = '') { return `SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*) FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published'${where} ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT ? OFFSET ?`; }
  async listReviews(limit, offset) { return this.db.prepare(this._reviewSelect()).all(limit, offset); }
  async listReviewsByRating(rating, limit, offset) { return this.db.prepare(this._reviewSelect(' AND r.rating=?')).all(rating, limit, offset); }
  async listReviewsByProduct(productId, limit, offset) { return this.db.prepare(this._reviewSelect(' AND r.review_product_id=?')).all(productId, limit, offset); }
  async listReviewsByProductAndRating(productId, rating, limit, offset) { return this.db.prepare(this._reviewSelect(' AND r.review_product_id=? AND r.rating=?')).all(productId, rating, limit, offset); }
  async reviewCountByRating(rating) { return this.db.prepare("SELECT COUNT(*) AS count FROM reviews WHERE status='published' AND rating=?").get(rating) || { count: 0 }; }
  async reviewCountByProductAndRating(productId, rating) { return this.db.prepare("SELECT COUNT(*) AS count FROM reviews WHERE status='published' AND review_product_id=? AND rating=?").get(productId, rating) || { count: 0 }; }
  async reviewSummary() { return this.db.prepare(`SELECT COUNT(*) AS count,COALESCE(AVG(rating),0) AS average,SUM(CASE WHEN rating=5 THEN 1 ELSE 0 END) AS rating_5,SUM(CASE WHEN rating=4 THEN 1 ELSE 0 END) AS rating_4,SUM(CASE WHEN rating=3 THEN 1 ELSE 0 END) AS rating_3,SUM(CASE WHEN rating=2 THEN 1 ELSE 0 END) AS rating_2,SUM(CASE WHEN rating=1 THEN 1 ELSE 0 END) AS rating_1 FROM reviews WHERE status='published'`).get(); }
  async reviewSummaryByProduct(productId) { return this.db.prepare(`SELECT COUNT(*) AS count,COALESCE(AVG(rating),0) AS average,SUM(CASE WHEN rating=5 THEN 1 ELSE 0 END) AS rating_5,SUM(CASE WHEN rating=4 THEN 1 ELSE 0 END) AS rating_4,SUM(CASE WHEN rating=3 THEN 1 ELSE 0 END) AS rating_3,SUM(CASE WHEN rating=2 THEN 1 ELSE 0 END) AS rating_2,SUM(CASE WHEN rating=1 THEN 1 ELSE 0 END) AS rating_1 FROM reviews WHERE status='published' AND review_product_id=?`).get(productId); }
  async insertReview(v) { const r=this.db.prepare(`INSERT INTO reviews (user_id,review_name,contact_phone,verified_purchase,review_product_id,review_product_variant,rating,body,review_date,status,created_at,updated_at) VALUES (?,?,?,1,?,?,?,?,?,'published',?,?)`).run(v.userId,v.reviewName,v.contactPhone,v.reviewProductId,v.reviewProductVariant,v.rating,v.body,v.reviewDate,v.createdAt,v.updatedAt); return Number(r.lastInsertRowid); }
  async insertReviewMedia(reviewId, sortOrder, blob, mime, kind, createdAt) { this.db.prepare(`INSERT INTO review_images (review_id,sort_order,image_blob,image_mime,media_kind,created_at) VALUES (?,?,?,?,?,?)`).run(reviewId,sortOrder,blob,mime,kind,createdAt); }
  async getReviewMedia(reviewId, sortOrder) { return this.db.prepare(`SELECT ri.image_blob,ri.image_mime,ri.media_kind FROM review_images ri JOIN reviews r ON r.id=ri.review_id WHERE ri.review_id=? AND ri.sort_order=? AND r.status='published' LIMIT 1`).get(reviewId,sortOrder) || null; }
  async listReviewMediaMeta(reviewId) { return this.db.prepare('SELECT sort_order,image_mime,media_kind FROM review_images WHERE review_id=? ORDER BY sort_order').all(reviewId); }

  async insertPendingOrder(v) { const r=this.db.prepare(`INSERT INTO orders (order_ref,user_id,customer_email,customer_phone,amount_agorot,currency,items_json,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'pending',?,?)`).run(v.orderRef,v.userId,v.customerEmail,v.customerPhone,v.amountAgorot,v.currency,v.itemsJson,v.createdAt,v.updatedAt); return Number(r.lastInsertRowid); }
  async getOrderByRef(ref) { return this.db.prepare('SELECT id,order_ref,user_id,amount_agorot,status FROM orders WHERE order_ref=? LIMIT 1').get(ref) || null; }
  async latestPaidOrderForUser(userId) { return this.db.prepare("SELECT id,items_json FROM orders WHERE user_id=? AND status='paid' ORDER BY COALESCE(paid_at,created_at) DESC,id DESC LIMIT 1").get(userId) || null; }
  async markOrderPaid(now, orderId) { this.db.prepare("UPDATE orders SET status='paid',paid_at=COALESCE(paid_at,?),updated_at=? WHERE id=?").run(now,now,orderId); }
  async markOrderFailed(now, orderId) { this.db.prepare("UPDATE orders SET status='failed',updated_at=? WHERE id=? AND status='pending'").run(now,orderId); }
  async markUserVerified(now, userId) { this.db.prepare('UPDATE users SET is_verified_customer=1,verified_customer_at=COALESCE(verified_customer_at,?) WHERE id=?').run(now,userId); }

  async listOrdersForAnalytics(status = 'paid', since = null) {
    return this.db.prepare(`
      SELECT id,order_ref,user_id,customer_email,customer_phone,amount_agorot,currency,items_json,status,created_at,paid_at,updated_at
      FROM orders
      WHERE status=? AND (? IS NULL OR COALESCE(paid_at,created_at)>=?)
      ORDER BY COALESCE(paid_at,created_at) DESC,id DESC
    `).all(status, since, since);
  }

  async listAdminOrders({ status = 'paid', since = null, limit = 50, offset = 0 } = {}) {
    return this.db.prepare(`
      SELECT o.id,o.order_ref,o.user_id,o.customer_email,o.customer_phone,o.amount_agorot,o.currency,o.items_json,o.status,o.created_at,o.paid_at,o.updated_at,
        u.name AS user_name,u.email AS user_email
      FROM orders o
      LEFT JOIN users u ON u.id=o.user_id
      WHERE (?='all' OR o.status=?) AND (? IS NULL OR COALESCE(o.paid_at,o.created_at)>=?)
      ORDER BY COALESCE(o.paid_at,o.created_at) DESC,o.id DESC
      LIMIT ? OFFSET ?
    `).all(status, status, since, since, limit, offset);
  }

  async countAdminOrders({ status = 'paid', since = null } = {}) {
    const row = this.db.prepare(`SELECT COUNT(*) AS count FROM orders WHERE (?='all' OR status=?) AND (? IS NULL OR COALESCE(paid_at,created_at)>=?)`).get(status, status, since, since);
    return Number(row ? row.count : 0);
  }

  async adminUserCounts() {
    const registered = this.db.prepare('SELECT COUNT(*) AS count FROM users').get();
    const paying = this.db.prepare("SELECT COUNT(DISTINCT user_id) AS count FROM orders WHERE status='paid' AND user_id IS NOT NULL").get();
    return { registeredUsers: Number(registered.count || 0), payingCustomers: Number(paying.count || 0) };
  }

  async listAdminCustomers(limit = 50, offset = 0) {
    return this.db.prepare(`
      SELECT u.id,u.name,u.email,u.is_verified_customer,u.verified_customer_at,u.created_at,
        COALESCE((SELECT COUNT(*) FROM orders o WHERE o.user_id=u.id AND o.status='paid'),0) AS paid_order_count,
        COALESCE((SELECT SUM(o.amount_agorot) FROM orders o WHERE o.user_id=u.id AND o.status='paid'),0) AS paid_spend_agorot,
        (SELECT MAX(COALESCE(o.paid_at,o.created_at)) FROM orders o WHERE o.user_id=u.id AND o.status='paid') AS last_paid_at,
        COALESCE(
          (SELECT o.customer_phone FROM orders o WHERE o.user_id=u.id AND o.customer_phone IS NOT NULL AND o.customer_phone<>'' ORDER BY COALESCE(o.paid_at,o.created_at) DESC,o.id DESC LIMIT 1),
          (SELECT r.contact_phone FROM reviews r WHERE r.user_id=u.id AND r.contact_phone IS NOT NULL AND r.contact_phone<>'' ORDER BY r.created_at DESC,r.id DESC LIMIT 1)
        ) AS known_phone
      FROM users u
      ORDER BY paid_spend_agorot DESC,paid_order_count DESC,u.created_at DESC,u.id DESC
      LIMIT ? OFFSET ?
    `).all(limit, offset);
  }

  async countAdminCustomers() {
    const row = this.db.prepare('SELECT COUNT(*) AS count FROM users').get();
    return Number(row ? row.count : 0);
  }

  async adminTrafficSummary(since = null) {
    const scalar = this.db.prepare('SELECT COUNT(*) AS count FROM visitor_page_views WHERE (? IS NULL OR viewed_at>=?)').get(since, since);
    const grouped = (field, table = 'visitor_page_views', timestampField = 'viewed_at', extraWhere = '') => this.db.prepare(`
      SELECT ${field} AS label,COUNT(*) AS count FROM ${table}
      WHERE (? IS NULL OR ${timestampField}>=?) ${extraWhere}
      GROUP BY ${field} ORDER BY count DESC,label ASC LIMIT 12
    `).all(since, since).map((row) => ({ label: row.label || '(ישיר / לא ידוע)', count: Number(row.count || 0) }));
    return {
      pageViews: Number(scalar ? scalar.count : 0),
      topPages: grouped('path'),
      entryPages: grouped('entry_path', 'visitor_presence', 'first_seen'),
      referrers: grouped('referrer', 'visitor_page_views', 'viewed_at', "AND referrer IS NOT NULL AND referrer<>''"),
      utmSources: grouped('utm_source', 'visitor_page_views', 'viewed_at', "AND utm_source IS NOT NULL AND utm_source<>''"),
      devices: grouped('device_type', 'visitor_presence', 'last_seen'),
      browsers: grouped('browser', 'visitor_presence', 'last_seen'),
      operatingSystems: grouped('os', 'visitor_presence', 'last_seen')
    };
  }

  async adminReviewSummary(since = null, limit = 20) {
    const summary = this.db.prepare(`
      SELECT COUNT(*) AS count,COALESCE(AVG(rating),0) AS average,
        SUM(CASE WHEN rating=5 THEN 1 ELSE 0 END) AS rating_5,
        SUM(CASE WHEN rating=4 THEN 1 ELSE 0 END) AS rating_4,
        SUM(CASE WHEN rating=3 THEN 1 ELSE 0 END) AS rating_3,
        SUM(CASE WHEN rating=2 THEN 1 ELSE 0 END) AS rating_2,
        SUM(CASE WHEN rating=1 THEN 1 ELSE 0 END) AS rating_1
      FROM reviews WHERE status='published' AND (? IS NULL OR COALESCE(review_date,created_at)>=?)
    `).get(since, since);
    const topProducts = this.db.prepare(`
      SELECT review_product_id AS product_id,COUNT(*) AS count,COALESCE(AVG(rating),0) AS average
      FROM reviews WHERE status='published' AND (? IS NULL OR COALESCE(review_date,created_at)>=?)
      GROUP BY review_product_id ORDER BY count DESC,average DESC LIMIT 12
    `).all(since, since);
    const recent = this.db.prepare(`
      SELECT r.id,r.user_id,r.review_name,r.review_product_id,r.review_product_variant,r.rating,r.body,r.verified_purchase,
        COALESCE(r.review_date,r.created_at) AS review_date,r.created_at,u.name AS user_name,u.email AS user_email
      FROM reviews r LEFT JOIN users u ON u.id=r.user_id
      WHERE r.status='published' AND (? IS NULL OR COALESCE(r.review_date,r.created_at)>=?)
      ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT ?
    `).all(since, since, limit);
    return { summary, topProducts, recent };
  }


  async recordPresence(v) {
    const pageViewIncrement = v.kind === 'pageview' ? 1 : 0;
    this.db.prepare(`
      INSERT INTO visitor_presence (
        visitor_id,user_id,is_authenticated,first_seen,last_seen,current_path,entry_path,last_title,referrer,
        utm_source,utm_medium,utm_campaign,utm_term,utm_content,language,browser,os,device_type,
        screen_width,screen_height,viewport_width,viewport_height,page_view_count
      ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
      ON CONFLICT(visitor_id) DO UPDATE SET
        user_id=COALESCE(excluded.user_id,visitor_presence.user_id),
        is_authenticated=excluded.is_authenticated,
        last_seen=excluded.last_seen,
        current_path=excluded.current_path,
        last_title=excluded.last_title,
        referrer=COALESCE(excluded.referrer,visitor_presence.referrer),
        utm_source=COALESCE(excluded.utm_source,visitor_presence.utm_source),
        utm_medium=COALESCE(excluded.utm_medium,visitor_presence.utm_medium),
        utm_campaign=COALESCE(excluded.utm_campaign,visitor_presence.utm_campaign),
        utm_term=COALESCE(excluded.utm_term,visitor_presence.utm_term),
        utm_content=COALESCE(excluded.utm_content,visitor_presence.utm_content),
        language=COALESCE(excluded.language,visitor_presence.language),
        browser=COALESCE(excluded.browser,visitor_presence.browser),
        os=COALESCE(excluded.os,visitor_presence.os),
        device_type=COALESCE(excluded.device_type,visitor_presence.device_type),
        screen_width=COALESCE(excluded.screen_width,visitor_presence.screen_width),
        screen_height=COALESCE(excluded.screen_height,visitor_presence.screen_height),
        viewport_width=COALESCE(excluded.viewport_width,visitor_presence.viewport_width),
        viewport_height=COALESCE(excluded.viewport_height,visitor_presence.viewport_height),
        page_view_count=visitor_presence.page_view_count+excluded.page_view_count
    `).run(
      v.visitorId, v.userId == null ? null : v.userId, v.userId == null ? 0 : 1, v.now, v.now, v.path, v.path, v.title, v.referrer,
      v.utmSource, v.utmMedium, v.utmCampaign, v.utmTerm, v.utmContent, v.language, v.browser, v.os, v.deviceType,
      v.screenWidth, v.screenHeight, v.viewportWidth, v.viewportHeight, pageViewIncrement
    );

    if (v.userId != null) {
      this.db.prepare('UPDATE visitor_page_views SET user_id=? WHERE visitor_id=? AND user_id IS NULL').run(v.userId, v.visitorId);
    }
    if (pageViewIncrement) {
      this.db.prepare(`INSERT INTO visitor_page_views (visitor_id,user_id,path,title,referrer,utm_source,utm_medium,utm_campaign,utm_term,utm_content,viewed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`)
        .run(v.visitorId, v.userId == null ? null : v.userId, v.path, v.title, v.referrer, v.utmSource, v.utmMedium, v.utmCampaign, v.utmTerm, v.utmContent, v.now);
    }
  }

  async countPresenceVisitors(since = null) {
    const row = this.db.prepare('SELECT COUNT(*) AS count FROM visitor_presence WHERE (? IS NULL OR last_seen>=?)').get(since, since);
    return Number(row ? row.count : 0);
  }

  async countPresenceVisitorsSince(since) { return this.countPresenceVisitors(since); }

  async listPresenceVisitors(since = null, limit = 50, offset = 0) {
    return this.db.prepare(`
      SELECT vp.*,
        u.name,u.email,u.is_verified_customer,u.verified_customer_at,u.created_at AS user_created_at,
        COALESCE(
          (SELECT o.customer_phone FROM orders o WHERE o.user_id=vp.user_id AND o.customer_phone IS NOT NULL AND o.customer_phone<>'' ORDER BY o.created_at DESC,o.id DESC LIMIT 1),
          (SELECT r.contact_phone FROM reviews r WHERE r.user_id=vp.user_id AND r.contact_phone IS NOT NULL AND r.contact_phone<>'' ORDER BY r.created_at DESC,r.id DESC LIMIT 1)
        ) AS known_phone
      FROM visitor_presence vp
      LEFT JOIN users u ON u.id=vp.user_id
      WHERE (? IS NULL OR vp.last_seen>=?)
      ORDER BY vp.last_seen DESC
      LIMIT ? OFFSET ?
    `).all(since, since, limit, offset);
  }

  async getPresenceVisitor(visitorId, pageLimit = 200) {
    const visitor = this.db.prepare(`
      SELECT vp.*,
        u.name,u.email,u.is_verified_customer,u.verified_customer_at,u.created_at AS user_created_at,
        COALESCE(
          (SELECT o.customer_phone FROM orders o WHERE o.user_id=vp.user_id AND o.customer_phone IS NOT NULL AND o.customer_phone<>'' ORDER BY o.created_at DESC,o.id DESC LIMIT 1),
          (SELECT r.contact_phone FROM reviews r WHERE r.user_id=vp.user_id AND r.contact_phone IS NOT NULL AND r.contact_phone<>'' ORDER BY r.created_at DESC,r.id DESC LIMIT 1)
        ) AS known_phone,
        (SELECT COUNT(*) FROM orders o WHERE o.user_id=vp.user_id) AS order_count,
        (SELECT COUNT(*) FROM orders o WHERE o.user_id=vp.user_id AND o.status='paid') AS paid_order_count,
        (SELECT MAX(o.created_at) FROM orders o WHERE o.user_id=vp.user_id) AS last_order_at,
        (SELECT COUNT(*) FROM reviews r WHERE r.user_id=vp.user_id) AS review_count,
        (SELECT s.created_at FROM sessions s WHERE s.user_id=vp.user_id ORDER BY s.created_at DESC,s.id DESC LIMIT 1) AS session_created_at,
        (SELECT s.expires_at FROM sessions s WHERE s.user_id=vp.user_id ORDER BY s.created_at DESC,s.id DESC LIMIT 1) AS session_expires_at
      FROM visitor_presence vp
      LEFT JOIN users u ON u.id=vp.user_id
      WHERE vp.visitor_id=?
      LIMIT 1
    `).get(visitorId) || null;
    if (!visitor) return null;
    const pageViews = this.db.prepare(`
      SELECT id,user_id,path,title,referrer,utm_source,utm_medium,utm_campaign,utm_term,utm_content,viewed_at
      FROM visitor_page_views WHERE visitor_id=? ORDER BY viewed_at DESC,id DESC LIMIT ?
    `).all(visitorId, pageLimit);
    return { visitor, pageViews };
  }

  async cleanupPresencePageViews(before) {
    const pageViews = this.db.prepare('DELETE FROM visitor_page_views WHERE viewed_at<?').run(before);
    return Number(pageViews.changes || 0);
  }

  async tableCounts() {
    const out = {};
    for (const table of ['users','sessions','orders','reviews','review_images','schema_meta']) out[table] = Number(this.db.prepare(`SELECT COUNT(*) AS count FROM ${table}`).get().count);
    return out;
  }
}

class PostgresStore {
  constructor(databaseUrl, pgPool) {
    this.backend = 'postgres';
    this.databaseUrl = databaseUrl;
    this.pool = pgPool || null;
    this._ownsPool = !pgPool;
    this.client = null;
  }

  _ensurePool() {
    if (this.pool) return;
    const pg = require('pg');
    if (pg.types) pg.types.setTypeParser(20, (value) => Number(value));
    this.pool = new pg.Pool({ connectionString: this.databaseUrl, max: Number(process.env.PGPOOL_MAX || 5) });
  }

  async _query(text, params = []) { this._ensurePool(); return (this.client || this.pool).query(text, params); }

  async init() {
    await this._query(POSTGRES_SCHEMA_SQL);
    await this._query(`INSERT INTO schema_meta (key,value) VALUES ('schema_version','9') ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value`);
    await this.deleteExpiredSessions(Date.now());
    await applyProductReplacementReviewResets(this);
    return this;
  }

  async close() { if (this._ownsPool && this.pool) await this.pool.end(); }

  async getSchemaMeta(key) { const r = await this._query('SELECT value FROM schema_meta WHERE key=$1 LIMIT 1', [key]); return r.rows[0] ? String(r.rows[0].value) : null; }
  async setSchemaMeta(key, value) { await this._query(`INSERT INTO schema_meta (key,value) VALUES ($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value`, [key, String(value)]); }
  async deleteReviewsByProductIds(productIds) { if (!Array.isArray(productIds) || !productIds.length) return { reviews: 0 }; const r = await this._query('DELETE FROM reviews WHERE review_product_id = ANY($1::text[])', [productIds]); return { reviews: Number(r.rowCount || 0) }; }

  async transaction(fn) {
    this._ensurePool();
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      const tx = Object.create(this);
      tx.client = client;
      tx._ownsPool = false;
      const value = await fn(tx);
      await client.query('COMMIT');
      return value;
    } catch (err) {
      try { await client.query('ROLLBACK'); } catch (_) {}
      throw err;
    } finally { client.release(); }
  }

  async findUserByEmail(email) { const r=await this._query(`SELECT id,name,email,password_hash,is_verified_customer,verified_customer_at,created_at FROM users WHERE LOWER(email)=LOWER($1) LIMIT 1`,[email]); return r.rows[0]||null; }
  async findPublicUserBySession(hash, now) { const r=await this._query(`SELECT u.id,u.name,u.email,u.is_verified_customer,u.verified_customer_at,u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>$2 LIMIT 1`,[hash,now]); return r.rows[0]||null; }
  async insertUser(name,email,passwordHash,createdAt) { const r=await this._query(`INSERT INTO users (name,email,password_hash,created_at) VALUES ($1,$2,$3,$4) RETURNING id`,[name,email,passwordHash,createdAt]); return Number(r.rows[0].id); }
  async insertSession(userId,hash,createdAt,expiresAt) { await this._query(`INSERT INTO sessions (user_id,token_hash,created_at,expires_at) VALUES ($1,$2,$3,$4)`,[userId,hash,createdAt,expiresAt]); }
  async deleteSession(hash) { await this._query('DELETE FROM sessions WHERE token_hash=$1',[hash]); }
  async deleteExpiredSessions(now) { await this._query('DELETE FROM sessions WHERE expires_at<=$1',[now]); }

  _reviewSelect(where='') { return `SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*)::int FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published'${where} ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $${where.includes('$2')?3:where.includes('$1')?2:1} OFFSET $${where.includes('$2')?4:where.includes('$1')?3:2}`; }
  async listReviews(limit,offset) { const r=await this._query(`SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*)::int FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published' ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $1 OFFSET $2`,[limit,offset]); return r.rows; }
  async listReviewsByRating(rating,limit,offset) { const r=await this._query(`SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*)::int FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published' AND r.rating=$1 ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $2 OFFSET $3`,[rating,limit,offset]); return r.rows; }
  async listReviewsByProduct(productId,limit,offset) { const r=await this._query(`SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*)::int FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published' AND r.review_product_id=$1 ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $2 OFFSET $3`,[productId,limit,offset]); return r.rows; }
  async listReviewsByProductAndRating(productId,rating,limit,offset) { const r=await this._query(`SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*)::int FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published' AND r.review_product_id=$1 AND r.rating=$2 ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $3 OFFSET $4`,[productId,rating,limit,offset]); return r.rows; }
  async reviewCountByRating(rating) { const r=await this._query(`SELECT COUNT(*)::int AS count FROM reviews WHERE status='published' AND rating=$1`,[rating]); return r.rows[0]||{count:0}; }
  async reviewCountByProductAndRating(productId,rating) { const r=await this._query(`SELECT COUNT(*)::int AS count FROM reviews WHERE status='published' AND review_product_id=$1 AND rating=$2`,[productId,rating]); return r.rows[0]||{count:0}; }
  async _summary(where='',params=[]) { const r=await this._query(`SELECT COUNT(*)::int AS count,COALESCE(AVG(rating),0)::float8 AS average,SUM(CASE WHEN rating=5 THEN 1 ELSE 0 END)::int AS rating_5,SUM(CASE WHEN rating=4 THEN 1 ELSE 0 END)::int AS rating_4,SUM(CASE WHEN rating=3 THEN 1 ELSE 0 END)::int AS rating_3,SUM(CASE WHEN rating=2 THEN 1 ELSE 0 END)::int AS rating_2,SUM(CASE WHEN rating=1 THEN 1 ELSE 0 END)::int AS rating_1 FROM reviews WHERE status='published'${where}`,params); return r.rows[0]; }
  async reviewSummary() { return this._summary(); }
  async reviewSummaryByProduct(productId) { return this._summary(' AND review_product_id=$1',[productId]); }
  async insertReview(v) { const r=await this._query(`INSERT INTO reviews (user_id,review_name,contact_phone,verified_purchase,review_product_id,review_product_variant,rating,body,review_date,status,created_at,updated_at) VALUES ($1,$2,$3,1,$4,$5,$6,$7,$8,'published',$9,$10) RETURNING id`,[v.userId,v.reviewName,v.contactPhone,v.reviewProductId,v.reviewProductVariant,v.rating,v.body,v.reviewDate,v.createdAt,v.updatedAt]); return Number(r.rows[0].id); }
  async insertReviewMedia(reviewId,sortOrder,blob,mime,kind,createdAt) { await this._query(`INSERT INTO review_images (review_id,sort_order,image_blob,image_mime,media_kind,created_at) VALUES ($1,$2,$3,$4,$5,$6)`,[reviewId,sortOrder,blob,mime,kind,createdAt]); }
  async getReviewMedia(reviewId,sortOrder) { const r=await this._query(`SELECT ri.image_blob,ri.image_mime,ri.media_kind FROM review_images ri JOIN reviews rv ON rv.id=ri.review_id WHERE ri.review_id=$1 AND ri.sort_order=$2 AND rv.status='published' LIMIT 1`,[reviewId,sortOrder]); return r.rows[0]||null; }
  async listReviewMediaMeta(reviewId) { const r=await this._query('SELECT sort_order,image_mime,media_kind FROM review_images WHERE review_id=$1 ORDER BY sort_order',[reviewId]); return r.rows; }

  async insertPendingOrder(v) { const r=await this._query(`INSERT INTO orders (order_ref,user_id,customer_email,customer_phone,amount_agorot,currency,items_json,status,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,'pending',$8,$9) RETURNING id`,[v.orderRef,v.userId,v.customerEmail,v.customerPhone,v.amountAgorot,v.currency,v.itemsJson,v.createdAt,v.updatedAt]); return Number(r.rows[0].id); }
  async getOrderByRef(ref) { const r=await this._query('SELECT id,order_ref,user_id,amount_agorot,status FROM orders WHERE order_ref=$1 LIMIT 1',[ref]); return r.rows[0]||null; }
  async latestPaidOrderForUser(userId) { const r=await this._query(`SELECT id,items_json FROM orders WHERE user_id=$1 AND status='paid' ORDER BY COALESCE(paid_at,created_at) DESC,id DESC LIMIT 1`,[userId]); return r.rows[0]||null; }
  async markOrderPaid(now,orderId) { await this._query(`UPDATE orders SET status='paid',paid_at=COALESCE(paid_at,$1),updated_at=$2 WHERE id=$3`,[now,now,orderId]); }
  async markOrderFailed(now,orderId) { await this._query(`UPDATE orders SET status='failed',updated_at=$1 WHERE id=$2 AND status='pending'`,[now,orderId]); }
  async markUserVerified(now,userId) { await this._query('UPDATE users SET is_verified_customer=1,verified_customer_at=COALESCE(verified_customer_at,$1) WHERE id=$2',[now,userId]); }

  async listOrdersForAnalytics(status = 'paid', since = null) {
    const r = await this._query(`
      SELECT id,order_ref,user_id,customer_email,customer_phone,amount_agorot,currency,items_json,status,created_at,paid_at,updated_at
      FROM orders
      WHERE status=$1 AND ($2::bigint IS NULL OR COALESCE(paid_at,created_at)>=$2)
      ORDER BY COALESCE(paid_at,created_at) DESC,id DESC
    `, [status, since]);
    return r.rows;
  }

  async listAdminOrders({ status = 'paid', since = null, limit = 50, offset = 0 } = {}) {
    const r = await this._query(`
      SELECT o.id,o.order_ref,o.user_id,o.customer_email,o.customer_phone,o.amount_agorot,o.currency,o.items_json,o.status,o.created_at,o.paid_at,o.updated_at,
        u.name AS user_name,u.email AS user_email
      FROM orders o
      LEFT JOIN users u ON u.id=o.user_id
      WHERE ($1='all' OR o.status=$1) AND ($2::bigint IS NULL OR COALESCE(o.paid_at,o.created_at)>=$2)
      ORDER BY COALESCE(o.paid_at,o.created_at) DESC,o.id DESC
      LIMIT $3 OFFSET $4
    `, [status, since, limit, offset]);
    return r.rows;
  }

  async countAdminOrders({ status = 'paid', since = null } = {}) {
    const r = await this._query(`SELECT COUNT(*)::int AS count FROM orders WHERE ($1='all' OR status=$1) AND ($2::bigint IS NULL OR COALESCE(paid_at,created_at)>=$2)`, [status, since]);
    return Number(r.rows[0] ? r.rows[0].count : 0);
  }

  async adminUserCounts() {
    const r = await this._query(`
      SELECT (SELECT COUNT(*)::int FROM users) AS registered_users,
        (SELECT COUNT(DISTINCT user_id)::int FROM orders WHERE status='paid' AND user_id IS NOT NULL) AS paying_customers
    `);
    const row = r.rows[0] || {};
    return { registeredUsers: Number(row.registered_users || 0), payingCustomers: Number(row.paying_customers || 0) };
  }

  async listAdminCustomers(limit = 50, offset = 0) {
    const r = await this._query(`
      SELECT u.id,u.name,u.email,u.is_verified_customer,u.verified_customer_at,u.created_at,
        COALESCE((SELECT COUNT(*)::int FROM orders o WHERE o.user_id=u.id AND o.status='paid'),0)::int AS paid_order_count,
        COALESCE((SELECT SUM(o.amount_agorot) FROM orders o WHERE o.user_id=u.id AND o.status='paid'),0)::bigint AS paid_spend_agorot,
        (SELECT MAX(COALESCE(o.paid_at,o.created_at)) FROM orders o WHERE o.user_id=u.id AND o.status='paid') AS last_paid_at,
        COALESCE(
          (SELECT o.customer_phone FROM orders o WHERE o.user_id=u.id AND o.customer_phone IS NOT NULL AND o.customer_phone<>'' ORDER BY COALESCE(o.paid_at,o.created_at) DESC,o.id DESC LIMIT 1),
          (SELECT rv.contact_phone FROM reviews rv WHERE rv.user_id=u.id AND rv.contact_phone IS NOT NULL AND rv.contact_phone<>'' ORDER BY rv.created_at DESC,rv.id DESC LIMIT 1)
        ) AS known_phone
      FROM users u
      ORDER BY paid_spend_agorot DESC,paid_order_count DESC,u.created_at DESC,u.id DESC
      LIMIT $1 OFFSET $2
    `, [limit, offset]);
    return r.rows.map((row) => ({ ...row, paid_order_count: Number(row.paid_order_count || 0), paid_spend_agorot: Number(row.paid_spend_agorot || 0) }));
  }

  async countAdminCustomers() {
    const r = await this._query('SELECT COUNT(*)::int AS count FROM users');
    return Number(r.rows[0] ? r.rows[0].count : 0);
  }

  async adminTrafficSummary(since = null) {
    const scalar = await this._query('SELECT COUNT(*)::int AS count FROM visitor_page_views WHERE ($1::bigint IS NULL OR viewed_at>=$1)', [since]);
    const grouped = async (field, table = 'visitor_page_views', timestampField = 'viewed_at', extraWhere = '') => {
      const r = await this._query(`SELECT ${field} AS label,COUNT(*)::int AS count FROM ${table} WHERE ($1::bigint IS NULL OR ${timestampField}>=$1) ${extraWhere} GROUP BY ${field} ORDER BY count DESC,label ASC LIMIT 12`, [since]);
      return r.rows.map((row) => ({ label: row.label || '(ישיר / לא ידוע)', count: Number(row.count || 0) }));
    };
    const [topPages, entryPages, referrers, utmSources, devices, browsers, operatingSystems] = await Promise.all([
      grouped('path'), grouped('entry_path','visitor_presence','first_seen'),
      grouped('referrer','visitor_page_views','viewed_at',"AND referrer IS NOT NULL AND referrer<>''"),
      grouped('utm_source','visitor_page_views','viewed_at',"AND utm_source IS NOT NULL AND utm_source<>''"),
      grouped('device_type','visitor_presence','last_seen'), grouped('browser','visitor_presence','last_seen'), grouped('os','visitor_presence','last_seen')
    ]);
    return { pageViews: Number(scalar.rows[0] ? scalar.rows[0].count : 0), topPages, entryPages, referrers, utmSources, devices, browsers, operatingSystems };
  }

  async adminReviewSummary(since = null, limit = 20) {
    const summaryResult = await this._query(`
      SELECT COUNT(*)::int AS count,COALESCE(AVG(rating),0)::float8 AS average,
        SUM(CASE WHEN rating=5 THEN 1 ELSE 0 END)::int AS rating_5,
        SUM(CASE WHEN rating=4 THEN 1 ELSE 0 END)::int AS rating_4,
        SUM(CASE WHEN rating=3 THEN 1 ELSE 0 END)::int AS rating_3,
        SUM(CASE WHEN rating=2 THEN 1 ELSE 0 END)::int AS rating_2,
        SUM(CASE WHEN rating=1 THEN 1 ELSE 0 END)::int AS rating_1
      FROM reviews WHERE status='published' AND ($1::bigint IS NULL OR COALESCE(review_date,created_at)>=$1)
    `, [since]);
    const topResult = await this._query(`
      SELECT review_product_id AS product_id,COUNT(*)::int AS count,COALESCE(AVG(rating),0)::float8 AS average
      FROM reviews WHERE status='published' AND ($1::bigint IS NULL OR COALESCE(review_date,created_at)>=$1)
      GROUP BY review_product_id ORDER BY count DESC,average DESC LIMIT 12
    `, [since]);
    const recentResult = await this._query(`
      SELECT r.id,r.user_id,r.review_name,r.review_product_id,r.review_product_variant,r.rating,r.body,r.verified_purchase,
        COALESCE(r.review_date,r.created_at) AS review_date,r.created_at,u.name AS user_name,u.email AS user_email
      FROM reviews r LEFT JOIN users u ON u.id=r.user_id
      WHERE r.status='published' AND ($1::bigint IS NULL OR COALESCE(r.review_date,r.created_at)>=$1)
      ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $2
    `, [since, limit]);
    return { summary: summaryResult.rows[0], topProducts: topResult.rows, recent: recentResult.rows };
  }


  async recordPresence(v) {
    const pageViewIncrement = v.kind === 'pageview' ? 1 : 0;
    await this._query(`
      INSERT INTO visitor_presence (
        visitor_id,user_id,is_authenticated,first_seen,last_seen,current_path,entry_path,last_title,referrer,
        utm_source,utm_medium,utm_campaign,utm_term,utm_content,language,browser,os,device_type,
        screen_width,screen_height,viewport_width,viewport_height,page_view_count
      ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23)
      ON CONFLICT(visitor_id) DO UPDATE SET
        user_id=COALESCE(EXCLUDED.user_id,visitor_presence.user_id),
        is_authenticated=EXCLUDED.is_authenticated,
        last_seen=EXCLUDED.last_seen,
        current_path=EXCLUDED.current_path,
        last_title=EXCLUDED.last_title,
        referrer=COALESCE(EXCLUDED.referrer,visitor_presence.referrer),
        utm_source=COALESCE(EXCLUDED.utm_source,visitor_presence.utm_source),
        utm_medium=COALESCE(EXCLUDED.utm_medium,visitor_presence.utm_medium),
        utm_campaign=COALESCE(EXCLUDED.utm_campaign,visitor_presence.utm_campaign),
        utm_term=COALESCE(EXCLUDED.utm_term,visitor_presence.utm_term),
        utm_content=COALESCE(EXCLUDED.utm_content,visitor_presence.utm_content),
        language=COALESCE(EXCLUDED.language,visitor_presence.language),
        browser=COALESCE(EXCLUDED.browser,visitor_presence.browser),
        os=COALESCE(EXCLUDED.os,visitor_presence.os),
        device_type=COALESCE(EXCLUDED.device_type,visitor_presence.device_type),
        screen_width=COALESCE(EXCLUDED.screen_width,visitor_presence.screen_width),
        screen_height=COALESCE(EXCLUDED.screen_height,visitor_presence.screen_height),
        viewport_width=COALESCE(EXCLUDED.viewport_width,visitor_presence.viewport_width),
        viewport_height=COALESCE(EXCLUDED.viewport_height,visitor_presence.viewport_height),
        page_view_count=visitor_presence.page_view_count+EXCLUDED.page_view_count
    `, [
      v.visitorId, v.userId == null ? null : v.userId, v.userId == null ? 0 : 1, v.now, v.now, v.path, v.path, v.title, v.referrer,
      v.utmSource, v.utmMedium, v.utmCampaign, v.utmTerm, v.utmContent, v.language, v.browser, v.os, v.deviceType,
      v.screenWidth, v.screenHeight, v.viewportWidth, v.viewportHeight, pageViewIncrement
    ]);
    if (v.userId != null) {
      await this._query('UPDATE visitor_page_views SET user_id=$1 WHERE visitor_id=$2 AND user_id IS NULL', [v.userId, v.visitorId]);
    }
    if (pageViewIncrement) {
      await this._query(`INSERT INTO visitor_page_views (visitor_id,user_id,path,title,referrer,utm_source,utm_medium,utm_campaign,utm_term,utm_content,viewed_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,
        [v.visitorId, v.userId == null ? null : v.userId, v.path, v.title, v.referrer, v.utmSource, v.utmMedium, v.utmCampaign, v.utmTerm, v.utmContent, v.now]);
    }
  }

  async countPresenceVisitors(since = null) {
    const r = await this._query('SELECT COUNT(*)::int AS count FROM visitor_presence WHERE ($1::bigint IS NULL OR last_seen>=$1)', [since]);
    return Number(r.rows[0] ? r.rows[0].count : 0);
  }

  async countPresenceVisitorsSince(since) { return this.countPresenceVisitors(since); }

  async listPresenceVisitors(since = null, limit = 50, offset = 0) {
    const r = await this._query(`
      SELECT vp.*,
        u.name,u.email,u.is_verified_customer,u.verified_customer_at,u.created_at AS user_created_at,
        COALESCE(
          (SELECT o.customer_phone FROM orders o WHERE o.user_id=vp.user_id AND o.customer_phone IS NOT NULL AND o.customer_phone<>'' ORDER BY o.created_at DESC,o.id DESC LIMIT 1),
          (SELECT rv.contact_phone FROM reviews rv WHERE rv.user_id=vp.user_id AND rv.contact_phone IS NOT NULL AND rv.contact_phone<>'' ORDER BY rv.created_at DESC,rv.id DESC LIMIT 1)
        ) AS known_phone
      FROM visitor_presence vp
      LEFT JOIN users u ON u.id=vp.user_id
      WHERE ($1::bigint IS NULL OR vp.last_seen>=$1)
      ORDER BY vp.last_seen DESC
      LIMIT $2 OFFSET $3
    `, [since, limit, offset]);
    return r.rows;
  }

  async getPresenceVisitor(visitorId, pageLimit = 200) {
    const r = await this._query(`
      SELECT vp.*,
        u.name,u.email,u.is_verified_customer,u.verified_customer_at,u.created_at AS user_created_at,
        COALESCE(
          (SELECT o.customer_phone FROM orders o WHERE o.user_id=vp.user_id AND o.customer_phone IS NOT NULL AND o.customer_phone<>'' ORDER BY o.created_at DESC,o.id DESC LIMIT 1),
          (SELECT rv.contact_phone FROM reviews rv WHERE rv.user_id=vp.user_id AND rv.contact_phone IS NOT NULL AND rv.contact_phone<>'' ORDER BY rv.created_at DESC,rv.id DESC LIMIT 1)
        ) AS known_phone,
        (SELECT COUNT(*)::int FROM orders o WHERE o.user_id=vp.user_id) AS order_count,
        (SELECT COUNT(*)::int FROM orders o WHERE o.user_id=vp.user_id AND o.status='paid') AS paid_order_count,
        (SELECT MAX(o.created_at) FROM orders o WHERE o.user_id=vp.user_id) AS last_order_at,
        (SELECT COUNT(*)::int FROM reviews rv WHERE rv.user_id=vp.user_id) AS review_count,
        (SELECT ss.created_at FROM sessions ss WHERE ss.user_id=vp.user_id ORDER BY ss.created_at DESC,ss.id DESC LIMIT 1) AS session_created_at,
        (SELECT ss.expires_at FROM sessions ss WHERE ss.user_id=vp.user_id ORDER BY ss.created_at DESC,ss.id DESC LIMIT 1) AS session_expires_at
      FROM visitor_presence vp
      LEFT JOIN users u ON u.id=vp.user_id
      WHERE vp.visitor_id=$1
      LIMIT 1
    `, [visitorId]);
    const visitor = r.rows[0] || null;
    if (!visitor) return null;
    const views = await this._query(`
      SELECT id,user_id,path,title,referrer,utm_source,utm_medium,utm_campaign,utm_term,utm_content,viewed_at
      FROM visitor_page_views WHERE visitor_id=$1 ORDER BY viewed_at DESC,id DESC LIMIT $2
    `, [visitorId, pageLimit]);
    return { visitor, pageViews: views.rows };
  }

  async cleanupPresencePageViews(before) {
    const pageViews = await this._query('DELETE FROM visitor_page_views WHERE viewed_at<$1', [before]);
    return Number(pageViews.rowCount || 0);
  }

  async tableCounts() {
    const out = {};
    for (const table of ['users','sessions','orders','reviews','review_images','schema_meta']) {
      const r=await this._query(`SELECT COUNT(*)::int AS count FROM ${table}`);
      out[table]=Number(r.rows[0].count);
    }
    return out;
  }
}

function createDatabase(options = {}) {
  const databaseUrl = options.databaseUrl !== undefined ? options.databaseUrl : (process.env.DATABASE_URL || '');
  if (databaseUrl) return new PostgresStore(databaseUrl, options.pgPool);
  const sqlitePath = options.sqlitePath || process.env.VERSANS_DB_PATH || path.join(options.root || process.cwd(), 'data', 'versans.sqlite');
  return new SqliteStore(path.resolve(sqlitePath));
}

module.exports = { createDatabase, SqliteStore, PostgresStore, POSTGRES_SCHEMA_SQL, ensureSqliteSchema };
