'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { DatabaseSync } = require('node:sqlite');

const POSTGRES_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  is_verified_customer INTEGER NOT NULL DEFAULT 0 CHECK (is_verified_customer IN (0,1)),
  verified_customer_at BIGINT,
  created_at BIGINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_nocase ON users (LOWER(email));

CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_ref TEXT NOT NULL UNIQUE,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  customer_email TEXT,
  customer_phone TEXT,
  amount_agorot INTEGER NOT NULL,
  currency TEXT NOT NULL DEFAULT 'ILS',
  items_json TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','failed')),
  created_at BIGINT NOT NULL,
  paid_at BIGINT,
  updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  review_name TEXT,
  contact_phone TEXT,
  verified_purchase INTEGER NOT NULL DEFAULT 0 CHECK (verified_purchase IN (0,1)),
  review_product_id TEXT,
  review_product_variant TEXT,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  body TEXT NOT NULL,
  review_date BIGINT,
  image_blob BYTEA,
  image_mime TEXT,
  status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('published','hidden')),
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS review_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id INTEGER NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,
  sort_order INTEGER NOT NULL,
  image_blob BYTEA NOT NULL,
  image_mime TEXT NOT NULL,
  media_kind TEXT NOT NULL DEFAULT 'image' CHECK (media_kind IN ('image','video')),
  created_at BIGINT NOT NULL,
  UNIQUE (review_id, sort_order)
);

CREATE TABLE IF NOT EXISTS schema_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_orders_ref ON orders(order_ref);
CREATE INDEX IF NOT EXISTS idx_orders_user_status ON orders(user_id, status);
CREATE INDEX IF NOT EXISTS idx_reviews_status_created_at ON reviews(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_review_images_review_order ON review_images(review_id, sort_order);
`;

function ensureSqliteSchema(db) {
  db.exec(`
    PRAGMA journal_mode = WAL;
    PRAGMA foreign_keys = ON;
    PRAGMA busy_timeout = 5000;

    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE COLLATE NOCASE,
      password_hash TEXT NOT NULL,
      is_verified_customer INTEGER NOT NULL DEFAULT 0 CHECK (is_verified_customer IN (0,1)),
      verified_customer_at INTEGER,
      created_at INTEGER NOT NULL
    );

    CREATE TABLE IF NOT EXISTS sessions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      token_hash TEXT NOT NULL UNIQUE,
      created_at INTEGER NOT NULL,
      expires_at INTEGER NOT NULL,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS orders (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      order_ref TEXT NOT NULL UNIQUE,
      user_id INTEGER,
      customer_email TEXT,
      customer_phone TEXT,
      amount_agorot INTEGER NOT NULL,
      currency TEXT NOT NULL DEFAULT 'ILS',
      items_json TEXT,
      status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','failed')),
      created_at INTEGER NOT NULL,
      paid_at INTEGER,
      updated_at INTEGER NOT NULL,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
    );

    CREATE TABLE IF NOT EXISTS reviews (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER NOT NULL,
      review_name TEXT,
      contact_phone TEXT,
      verified_purchase INTEGER NOT NULL DEFAULT 0 CHECK (verified_purchase IN (0,1)),
      review_product_id TEXT,
      review_product_variant TEXT,
      rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
      body TEXT NOT NULL,
      review_date INTEGER,
      image_blob BLOB,
      image_mime TEXT,
      status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('published','hidden')),
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS review_images (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      review_id INTEGER NOT NULL,
      sort_order INTEGER NOT NULL,
      image_blob BLOB NOT NULL,
      image_mime TEXT NOT NULL,
      media_kind TEXT NOT NULL DEFAULT 'image' CHECK (media_kind IN ('image','video')),
      created_at INTEGER NOT NULL,
      FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE,
      UNIQUE (review_id, sort_order)
    );

    CREATE TABLE IF NOT EXISTS schema_meta (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    );
  `);

  const addColumnIfMissing = (table, column, sql) => {
    const columns = db.prepare(`PRAGMA table_info(${table})`).all();
    if (!columns.some((item) => item.name === column)) db.exec(sql);
  };
  addColumnIfMissing('users', 'is_verified_customer', 'ALTER TABLE users ADD COLUMN is_verified_customer INTEGER NOT NULL DEFAULT 0 CHECK (is_verified_customer IN (0,1))');
  addColumnIfMissing('users', 'verified_customer_at', 'ALTER TABLE users ADD COLUMN verified_customer_at INTEGER');
  addColumnIfMissing('reviews', 'review_name', 'ALTER TABLE reviews ADD COLUMN review_name TEXT');
  addColumnIfMissing('reviews', 'review_date', 'ALTER TABLE reviews ADD COLUMN review_date INTEGER');
  addColumnIfMissing('reviews', 'contact_phone', 'ALTER TABLE reviews ADD COLUMN contact_phone TEXT');
  addColumnIfMissing('reviews', 'verified_purchase', 'ALTER TABLE reviews ADD COLUMN verified_purchase INTEGER NOT NULL DEFAULT 0 CHECK (verified_purchase IN (0,1))');
  addColumnIfMissing('reviews', 'review_product_id', 'ALTER TABLE reviews ADD COLUMN review_product_id TEXT');
  addColumnIfMissing('reviews', 'review_product_variant', 'ALTER TABLE reviews ADD COLUMN review_product_variant TEXT');
  addColumnIfMissing('review_images', 'media_kind', "ALTER TABLE review_images ADD COLUMN media_kind TEXT NOT NULL DEFAULT 'image' CHECK (media_kind IN ('image','video'))");

  db.exec(`
    CREATE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash);
    CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);
    CREATE INDEX IF NOT EXISTS idx_orders_ref ON orders(order_ref);
    CREATE INDEX IF NOT EXISTS idx_orders_user_status ON orders(user_id, status);
    CREATE INDEX IF NOT EXISTS idx_reviews_status_created_at ON reviews(status, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_review_images_review_order ON review_images(review_id, sort_order);
    UPDATE reviews SET review_name = 'לקוח VerSans';
    UPDATE reviews SET review_date = created_at WHERE review_date IS NULL;
    UPDATE reviews SET review_product_id = 'mom-heart-01' WHERE review_product_id IS NULL OR review_product_id = '';
    INSERT INTO review_images (review_id, sort_order, image_blob, image_mime, media_kind, created_at)
      SELECT r.id, 0, r.image_blob, r.image_mime, 'image', r.created_at
      FROM reviews r
      WHERE r.image_blob IS NOT NULL AND r.image_mime IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM review_images ri WHERE ri.review_id = r.id);
    INSERT INTO schema_meta (key, value) VALUES ('schema_version', '8')
      ON CONFLICT(key) DO UPDATE SET value = excluded.value;
  `);
}

class SqliteStore {
  constructor(sqlitePath) {
    this.backend = 'sqlite';
    this.sqlitePath = sqlitePath;
    this.db = null;
  }

  async init() {
    fs.mkdirSync(path.dirname(this.sqlitePath), { recursive: true });
    this.db = new DatabaseSync(this.sqlitePath);
    ensureSqliteSchema(this.db);
    await this.deleteExpiredSessions(Date.now());
    return this;
  }

  async close() { if (this.db) { this.db.close(); this.db = null; } }

  async transaction(fn) {
    this.db.exec('BEGIN IMMEDIATE');
    try {
      const value = await fn(this);
      this.db.exec('COMMIT');
      return value;
    } catch (err) {
      try { this.db.exec('ROLLBACK'); } catch (_) {}
      throw err;
    }
  }

  async findUserByEmail(email) { return this.db.prepare(`SELECT id, name, email, password_hash, is_verified_customer, verified_customer_at, created_at FROM users WHERE email = ? COLLATE NOCASE LIMIT 1`).get(email) || null; }
  async findPublicUserBySession(hash, now) { return this.db.prepare(`SELECT u.id, u.name, u.email, u.is_verified_customer, u.verified_customer_at, u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? LIMIT 1`).get(hash, now) || null; }
  async insertUser(name, email, passwordHash, createdAt) { const r = this.db.prepare('INSERT INTO users (name,email,password_hash,created_at) VALUES (?,?,?,?)').run(name,email,passwordHash,createdAt); return Number(r.lastInsertRowid); }
  async insertSession(userId, tokenHash, createdAt, expiresAt) { this.db.prepare('INSERT INTO sessions (user_id,token_hash,created_at,expires_at) VALUES (?,?,?,?)').run(userId,tokenHash,createdAt,expiresAt); }
  async deleteSession(hash) { this.db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash); }
  async deleteExpiredSessions(now) { this.db.prepare('DELETE FROM sessions WHERE expires_at<=?').run(now); }

  _reviewSelect(where = '') { return `SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*) FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published'${where} ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT ? OFFSET ?`; }
  async listReviews(limit, offset) { return this.db.prepare(this._reviewSelect()).all(limit, offset); }
  async listReviewsByRating(rating, limit, offset) { return this.db.prepare(this._reviewSelect(' AND r.rating=?')).all(rating, limit, offset); }
  async listReviewsByProduct(productId, limit, offset) { return this.db.prepare(this._reviewSelect(' AND r.review_product_id=?')).all(productId, limit, offset); }
  async listReviewsByProductAndRating(productId, rating, limit, offset) { return this.db.prepare(this._reviewSelect(' AND r.review_product_id=? AND r.rating=?')).all(productId, rating, limit, offset); }
  async reviewCountByRating(rating) { return this.db.prepare("SELECT COUNT(*) AS count FROM reviews WHERE status='published' AND rating=?").get(rating) || { count: 0 }; }
  async reviewCountByProductAndRating(productId, rating) { return this.db.prepare("SELECT COUNT(*) AS count FROM reviews WHERE status='published' AND review_product_id=? AND rating=?").get(productId, rating) || { count: 0 }; }
  async reviewSummary() { return this.db.prepare(`SELECT COUNT(*) AS count,COALESCE(AVG(rating),0) AS average,SUM(CASE WHEN rating=5 THEN 1 ELSE 0 END) AS rating_5,SUM(CASE WHEN rating=4 THEN 1 ELSE 0 END) AS rating_4,SUM(CASE WHEN rating=3 THEN 1 ELSE 0 END) AS rating_3,SUM(CASE WHEN rating=2 THEN 1 ELSE 0 END) AS rating_2,SUM(CASE WHEN rating=1 THEN 1 ELSE 0 END) AS rating_1 FROM reviews WHERE status='published'`).get(); }
  async reviewSummaryByProduct(productId) { return this.db.prepare(`SELECT COUNT(*) AS count,COALESCE(AVG(rating),0) AS average,SUM(CASE WHEN rating=5 THEN 1 ELSE 0 END) AS rating_5,SUM(CASE WHEN rating=4 THEN 1 ELSE 0 END) AS rating_4,SUM(CASE WHEN rating=3 THEN 1 ELSE 0 END) AS rating_3,SUM(CASE WHEN rating=2 THEN 1 ELSE 0 END) AS rating_2,SUM(CASE WHEN rating=1 THEN 1 ELSE 0 END) AS rating_1 FROM reviews WHERE status='published' AND review_product_id=?`).get(productId); }
  async insertReview(v) { const r=this.db.prepare(`INSERT INTO reviews (user_id,review_name,contact_phone,verified_purchase,review_product_id,review_product_variant,rating,body,review_date,status,created_at,updated_at) VALUES (?,?,?,1,?,?,?,?,?,'published',?,?)`).run(v.userId,v.reviewName,v.contactPhone,v.reviewProductId,v.reviewProductVariant,v.rating,v.body,v.reviewDate,v.createdAt,v.updatedAt); return Number(r.lastInsertRowid); }
  async insertReviewMedia(reviewId, sortOrder, blob, mime, kind, createdAt) { this.db.prepare(`INSERT INTO review_images (review_id,sort_order,image_blob,image_mime,media_kind,created_at) VALUES (?,?,?,?,?,?)`).run(reviewId,sortOrder,blob,mime,kind,createdAt); }
  async getReviewMedia(reviewId, sortOrder) { return this.db.prepare(`SELECT ri.image_blob,ri.image_mime,ri.media_kind FROM review_images ri JOIN reviews r ON r.id=ri.review_id WHERE ri.review_id=? AND ri.sort_order=? AND r.status='published' LIMIT 1`).get(reviewId,sortOrder) || null; }
  async listReviewMediaMeta(reviewId) { return this.db.prepare('SELECT sort_order,image_mime,media_kind FROM review_images WHERE review_id=? ORDER BY sort_order').all(reviewId); }

  async insertPendingOrder(v) { const r=this.db.prepare(`INSERT INTO orders (order_ref,user_id,customer_email,customer_phone,amount_agorot,currency,items_json,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'pending',?,?)`).run(v.orderRef,v.userId,v.customerEmail,v.customerPhone,v.amountAgorot,v.currency,v.itemsJson,v.createdAt,v.updatedAt); return Number(r.lastInsertRowid); }
  async getOrderByRef(ref) { return this.db.prepare('SELECT id,order_ref,user_id,amount_agorot,status FROM orders WHERE order_ref=? LIMIT 1').get(ref) || null; }
  async latestPaidOrderForUser(userId) { return this.db.prepare("SELECT id,items_json FROM orders WHERE user_id=? AND status='paid' ORDER BY COALESCE(paid_at,created_at) DESC,id DESC LIMIT 1").get(userId) || null; }
  async markOrderPaid(now, orderId) { this.db.prepare("UPDATE orders SET status='paid',paid_at=COALESCE(paid_at,?),updated_at=? WHERE id=?").run(now,now,orderId); }
  async markOrderFailed(now, orderId) { this.db.prepare("UPDATE orders SET status='failed',updated_at=? WHERE id=? AND status='pending'").run(now,orderId); }
  async markUserVerified(now, userId) { this.db.prepare('UPDATE users SET is_verified_customer=1,verified_customer_at=COALESCE(verified_customer_at,?) WHERE id=?').run(now,userId); }

  async tableCounts() {
    const out = {};
    for (const table of ['users','sessions','orders','reviews','review_images','schema_meta']) out[table] = Number(this.db.prepare(`SELECT COUNT(*) AS count FROM ${table}`).get().count);
    return out;
  }
}

class PostgresStore {
  constructor(databaseUrl, pgPool) {
    this.backend = 'postgres';
    this.databaseUrl = databaseUrl;
    this.pool = pgPool || null;
    this._ownsPool = !pgPool;
    this.client = null;
  }

  _ensurePool() {
    if (this.pool) return;
    const pg = require('pg');
    if (pg.types) pg.types.setTypeParser(20, (value) => Number(value));
    this.pool = new pg.Pool({ connectionString: this.databaseUrl, max: Number(process.env.PGPOOL_MAX || 5) });
  }

  async _query(text, params = []) { this._ensurePool(); return (this.client || this.pool).query(text, params); }

  async init() {
    await this._query(POSTGRES_SCHEMA_SQL);
    await this._query(`INSERT INTO schema_meta (key,value) VALUES ('schema_version','8') ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value`);
    await this.deleteExpiredSessions(Date.now());
    return this;
  }

  async close() { if (this._ownsPool && this.pool) await this.pool.end(); }

  async transaction(fn) {
    this._ensurePool();
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');
      const tx = Object.create(this);
      tx.client = client;
      tx._ownsPool = false;
      const value = await fn(tx);
      await client.query('COMMIT');
      return value;
    } catch (err) {
      try { await client.query('ROLLBACK'); } catch (_) {}
      throw err;
    } finally { client.release(); }
  }

  async findUserByEmail(email) { const r=await this._query(`SELECT id,name,email,password_hash,is_verified_customer,verified_customer_at,created_at FROM users WHERE LOWER(email)=LOWER($1) LIMIT 1`,[email]); return r.rows[0]||null; }
  async findPublicUserBySession(hash, now) { const r=await this._query(`SELECT u.id,u.name,u.email,u.is_verified_customer,u.verified_customer_at,u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>$2 LIMIT 1`,[hash,now]); return r.rows[0]||null; }
  async insertUser(name,email,passwordHash,createdAt) { const r=await this._query(`INSERT INTO users (name,email,password_hash,created_at) VALUES ($1,$2,$3,$4) RETURNING id`,[name,email,passwordHash,createdAt]); return Number(r.rows[0].id); }
  async insertSession(userId,hash,createdAt,expiresAt) { await this._query(`INSERT INTO sessions (user_id,token_hash,created_at,expires_at) VALUES ($1,$2,$3,$4)`,[userId,hash,createdAt,expiresAt]); }
  async deleteSession(hash) { await this._query('DELETE FROM sessions WHERE token_hash=$1',[hash]); }
  async deleteExpiredSessions(now) { await this._query('DELETE FROM sessions WHERE expires_at<=$1',[now]); }

  _reviewSelect(where='') { return `SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*)::int FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published'${where} ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $${where.includes('$2')?3:where.includes('$1')?2:1} OFFSET $${where.includes('$2')?4:where.includes('$1')?3:2}`; }
  async listReviews(limit,offset) { const r=await this._query(`SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*)::int FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published' ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $1 OFFSET $2`,[limit,offset]); return r.rows; }
  async listReviewsByRating(rating,limit,offset) { const r=await this._query(`SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*)::int FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published' AND r.rating=$1 ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $2 OFFSET $3`,[rating,limit,offset]); return r.rows; }
  async listReviewsByProduct(productId,limit,offset) { const r=await this._query(`SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*)::int FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published' AND r.review_product_id=$1 ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $2 OFFSET $3`,[productId,limit,offset]); return r.rows; }
  async listReviewsByProductAndRating(productId,rating,limit,offset) { const r=await this._query(`SELECT r.id,r.rating,r.body,r.created_at,r.updated_at,COALESCE(r.review_date,r.created_at) AS review_date,r.verified_purchase,r.review_product_id,r.review_product_variant,(SELECT COUNT(*)::int FROM review_images ri WHERE ri.review_id=r.id) AS media_count FROM reviews r WHERE r.status='published' AND r.review_product_id=$1 AND r.rating=$2 ORDER BY COALESCE(r.review_date,r.created_at) DESC,r.id DESC LIMIT $3 OFFSET $4`,[productId,rating,limit,offset]); return r.rows; }
  async reviewCountByRating(rating) { const r=await this._query(`SELECT COUNT(*)::int AS count FROM reviews WHERE status='published' AND rating=$1`,[rating]); return r.rows[0]||{count:0}; }
  async reviewCountByProductAndRating(productId,rating) { const r=await this._query(`SELECT COUNT(*)::int AS count FROM reviews WHERE status='published' AND review_product_id=$1 AND rating=$2`,[productId,rating]); return r.rows[0]||{count:0}; }
  async _summary(where='',params=[]) { const r=await this._query(`SELECT COUNT(*)::int AS count,COALESCE(AVG(rating),0)::float8 AS average,SUM(CASE WHEN rating=5 THEN 1 ELSE 0 END)::int AS rating_5,SUM(CASE WHEN rating=4 THEN 1 ELSE 0 END)::int AS rating_4,SUM(CASE WHEN rating=3 THEN 1 ELSE 0 END)::int AS rating_3,SUM(CASE WHEN rating=2 THEN 1 ELSE 0 END)::int AS rating_2,SUM(CASE WHEN rating=1 THEN 1 ELSE 0 END)::int AS rating_1 FROM reviews WHERE status='published'${where}`,params); return r.rows[0]; }
  async reviewSummary() { return this._summary(); }
  async reviewSummaryByProduct(productId) { return this._summary(' AND review_product_id=$1',[productId]); }
  async insertReview(v) { const r=await this._query(`INSERT INTO reviews (user_id,review_name,contact_phone,verified_purchase,review_product_id,review_product_variant,rating,body,review_date,status,created_at,updated_at) VALUES ($1,$2,$3,1,$4,$5,$6,$7,$8,'published',$9,$10) RETURNING id`,[v.userId,v.reviewName,v.contactPhone,v.reviewProductId,v.reviewProductVariant,v.rating,v.body,v.reviewDate,v.createdAt,v.updatedAt]); return Number(r.rows[0].id); }
  async insertReviewMedia(reviewId,sortOrder,blob,mime,kind,createdAt) { await this._query(`INSERT INTO review_images (review_id,sort_order,image_blob,image_mime,media_kind,created_at) VALUES ($1,$2,$3,$4,$5,$6)`,[reviewId,sortOrder,blob,mime,kind,createdAt]); }
  async getReviewMedia(reviewId,sortOrder) { const r=await this._query(`SELECT ri.image_blob,ri.image_mime,ri.media_kind FROM review_images ri JOIN reviews rv ON rv.id=ri.review_id WHERE ri.review_id=$1 AND ri.sort_order=$2 AND rv.status='published' LIMIT 1`,[reviewId,sortOrder]); return r.rows[0]||null; }
  async listReviewMediaMeta(reviewId) { const r=await this._query('SELECT sort_order,image_mime,media_kind FROM review_images WHERE review_id=$1 ORDER BY sort_order',[reviewId]); return r.rows; }

  async insertPendingOrder(v) { const r=await this._query(`INSERT INTO orders (order_ref,user_id,customer_email,customer_phone,amount_agorot,currency,items_json,status,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,'pending',$8,$9) RETURNING id`,[v.orderRef,v.userId,v.customerEmail,v.customerPhone,v.amountAgorot,v.currency,v.itemsJson,v.createdAt,v.updatedAt]); return Number(r.rows[0].id); }
  async getOrderByRef(ref) { const r=await this._query('SELECT id,order_ref,user_id,amount_agorot,status FROM orders WHERE order_ref=$1 LIMIT 1',[ref]); return r.rows[0]||null; }
  async latestPaidOrderForUser(userId) { const r=await this._query(`SELECT id,items_json FROM orders WHERE user_id=$1 AND status='paid' ORDER BY COALESCE(paid_at,created_at) DESC,id DESC LIMIT 1`,[userId]); return r.rows[0]||null; }
  async markOrderPaid(now,orderId) { await this._query(`UPDATE orders SET status='paid',paid_at=COALESCE(paid_at,$1),updated_at=$2 WHERE id=$3`,[now,now,orderId]); }
  async markOrderFailed(now,orderId) { await this._query(`UPDATE orders SET status='failed',updated_at=$1 WHERE id=$2 AND status='pending'`,[now,orderId]); }
  async markUserVerified(now,userId) { await this._query('UPDATE users SET is_verified_customer=1,verified_customer_at=COALESCE(verified_customer_at,$1) WHERE id=$2',[now,userId]); }

  async tableCounts() {
    const out = {};
    for (const table of ['users','sessions','orders','reviews','review_images','schema_meta']) {
      const r=await this._query(`SELECT COUNT(*)::int AS count FROM ${table}`);
      out[table]=Number(r.rows[0].count);
    }
    return out;
  }
}

function createDatabase(options = {}) {
  const databaseUrl = options.databaseUrl !== undefined ? options.databaseUrl : (process.env.DATABASE_URL || '');
  if (databaseUrl) return new PostgresStore(databaseUrl, options.pgPool);
  const sqlitePath = options.sqlitePath || process.env.VERSANS_DB_PATH || path.join(options.root || process.cwd(), 'data', 'versans.sqlite');
  return new SqliteStore(path.resolve(sqlitePath));
}

module.exports = { createDatabase, SqliteStore, PostgresStore, POSTGRES_SCHEMA_SQL, ensureSqliteSchema };
